[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[context.production.environment]
  SUPABASE_URL = "PLACEHOLDER_WILL_BE_REPLACED_BY_NETLIFY"
  SUPABASE_KEY = "PLACEHOLDER_WILL_BE_REPLACED_BY_NETLIFY"